apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "datapersisters.labels" . | indent 4 }}
    component: influxdb
  name: influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
{{ include "datapersisters.matchLabels" . | indent 6 }}
      component: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "datapersisters.labels" . | indent 8 }}
        component: influxdb
    spec:
      containers:
      - image: harbor.clarebout.com/library/influxdb:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: {{ .Values.persistence.influxdb.name }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.persistence.influxdb.name }}
        persistentVolumeClaim:
          claimName: influxdb-data-pvc
