apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-data-pvc
  annotations:
    helm.sh/resource-policy: "keep"
spec:
{{ toYaml .Values.persistence.jiraData.persistentVolumeClaim | indent 2 }}