apiVersion: v1
kind: Service
metadata:
  name: jira
  labels:
{{ include "atlassian-jira-software.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{ include "atlassian-jira-software.matchLabels" . | indent 4 }}
