apiVersion: v1
kind: Service
metadata:
  name: confluence
  labels:
{{ include "atlassian-confluence-server.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: http
    protocol: TCP
    name: http
  - port: 8091
    targetPort: http
    protocol: TCP
    name: synchrony
  selector:
{{ include "atlassian-confluence-server.matchLabels" . | indent 4 }}
    component: confluence
