apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "atlassian-postgres.labels" . | indent 4 }}
  name: postgres
spec:
  ports:
  - name: 5432tcp
    port: 5432
    protocol: TCP
  selector:
{{ include "atlassian-postgres.matchLabels" . | indent 4 }}
    component: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
